name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Install start-server-and-test
        run: npm install start-server-and-test

      - name: Start the app and run tests
        run: npx start-server-and-test start http://localhost:7070 cypress:run
